project:
  type: website
  output-dir: docs

website:
  title: "Daniel Benaya"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "All About Me"
        href: All_About_me/index.html
      - text: "My Stories"
        href: My_Stories_for_You/index.html
      - text: "Songs"
        href: My_Song_for_You/index.html
      - text: "Reviews"
        href: My_Personal_Reviews/index.html
      - text: "S.H.A.P.E"
        href: My_Shapes/index.html

format:
  html:
    theme: cosmo
    css: styles.css
