project:
  type: website
  output-dir: docs

website:
  title: "All About Me"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "UTS 1"
        href: All_About_me/index.qmd
      - text: "UTS 2"
        href: My_Song_for_You/index.qmd
      - text: "UTS 3"
        href: My_Stories_for_You/index.qmd
      - text: "UTS 4"
        href: My_Shapes/index.qmd
      - text: "UTS 5"
        href: My_Personal_Reviews/index.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: false
    page-layout: full
